// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs unzip`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "create-zip",
    "icon": "🗜️",
    "name": {
      "en": "Create ZIP",
      "ja": "ZIPを作成",
      "zh": "打包 ZIP",
      "de": "ZIP erstellen",
      "es": "Crear ZIP"
    },
    "desc": {
      "en": "Bundle your files into a single .zip archive.",
      "ja": "複数のファイルを1つの.zipにまとめます。",
      "zh": "把多个文件打包成一个 .zip 压缩包。",
      "de": "Deine Dateien zu einem einzigen .zip-Archiv bündeln.",
      "es": "Reúne tus archivos en un solo archivo .zip."
    }
  },
  {
    "slug": "zip-viewer",
    "icon": "👁️",
    "name": {
      "en": "ZIP Viewer",
      "ja": "ZIPの中身を確認",
      "zh": "查看 ZIP",
      "de": "ZIP-Viewer",
      "es": "Visor de ZIP"
    },
    "desc": {
      "en": "See what's inside a .zip without extracting it.",
      "ja": "展開せずに.zipの中身を確認します。",
      "zh": "不解压也能看 .zip 里面有什么。",
      "de": "Schau in ein .zip hinein, ohne es zu entpacken.",
      "es": "Ve qué contiene un .zip sin extraerlo."
    }
  },
  {
    "slug": "recover-zip",
    "icon": "🩹",
    "name": {
      "en": "Recover ZIP",
      "ja": "壊れたZip救出",
      "zh": "修复 ZIP",
      "de": "ZIP retten",
      "es": "Recuperar ZIP"
    },
    "desc": {
      "en": "Salvage files from a broken or corrupted .zip.",
      "ja": "壊れた/破損した .zip からファイルを救出。",
      "zh": "从损坏的 .zip 中抢救文件。",
      "de": "Dateien aus einem beschädigten .zip retten.",
      "es": "Rescata archivos de un .zip dañado."
    }
  },
  {
    "slug": "unlock-zip",
    "icon": "🔓",
    "name": {
      "en": "Unlock ZIP",
      "ja": "Zipパスワード解除",
      "zh": "解锁 ZIP",
      "de": "ZIP entsperren",
      "es": "Desbloquear ZIP"
    },
    "desc": {
      "en": "Remove the password from a .zip you can open.",
      "ja": "開けるパスワード付き .zip のパスワードを解除。",
      "zh": "移除你能打开的 .zip 的密码。",
      "de": "Das Passwort aus einem .zip entfernen, das du öffnen kannst.",
      "es": "Quita la contraseña de un .zip que puedas abrir."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'unzip';
